version: '3.8'

services:
  rag_api_fast:
    build:
      context: .
      dockerfile: Dockerfile.fast
    container_name: rag_api_fast
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=staging
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis_fast:
    image: redis:7-alpine
    container_name: redis_fast
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    name: rag_network_fast
