apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 5s
      incrementalQueryOverlapWindow: 10s

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    basicAuth: false
    version: 1
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        tags: ['trace_id']

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: 'trace_id=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    basicAuth: false
    version: 1
    editable: true
    jsonData:
      index: 'rag-logs-*'
      timeField: '@timestamp'
      esVersion: '8.0.0'
      includeFrozen: false
      logMessageField: 'message'
      logLevelField: 'level'
