http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# JVM settings
config.reload.automatic: true
config.reload.interval: 3s

# Logging
log.level: info
path.logs: /usr/share/logstash/logs

# Dead letter queue
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1024mb

# Performance tuning
pipeline.ordered: auto
