apiVersion: v2
name: enterprise-rag
description: A Helm chart for Enterprise RAG System
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - rag
  - llm
  - vector-database
  - ai
  - enterprise
home: https://github.com/yourorg/enterprise-rag
sources:
  - https://github.com/yourorg/enterprise-rag
maintainers:
  - name: DevOps Team
    email: devops@yourcompany.com

dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.4.3"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
