apiVersion: v1
kind: ConfigMap
metadata:
  name: enterprise-rag-config
  namespace: enterprise-rag
data:
  # Application settings
  APP_NAME: "Enterprise RAG System"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  
  # API settings
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  API_PREFIX: "/api/v1"
  
  # Database settings
  DATABASE_ECHO: "false"
  DATABASE_POOL_SIZE: "20"
  DATABASE_MAX_OVERFLOW: "30"
  
  # Redis settings
  REDIS_DB: "0"
  REDIS_MAX_CONNECTIONS: "50"
  
  # Vector Database settings
  QDRANT_HOST: "qdrant-service"
  QDRANT_PORT: "6333"
  QDRANT_COLLECTION_NAME: "enterprise_rag"
  WEAVIATE_URL: "http://weaviate-service:8080"
  VECTOR_DB_PROVIDER: "qdrant"
  
  # LLM settings
  OPENAI_MODEL: "gpt-4"
  OPENAI_TEMPERATURE: "0.1"
  OPENAI_MAX_TOKENS: "4000"
  COHERE_MODEL: "command-r-plus"
  OLLAMA_BASE_URL: "http://ollama-service:11434"
  OLLAMA_MODEL: "llama3:8b"
  EMBEDDING_MODEL: "text-embedding-3-large"
  EMBEDDING_DIMENSION: "3072"
  LLM_PROVIDER: "openai"
  
  # Processing settings
  CHUNK_SIZE: "1000"
  CHUNK_OVERLAP: "200"
  OCR_LANGUAGE: "eng"
  OCR_CONFIDENCE_THRESHOLD: "0.7"
  WHISPER_MODEL: "base"
  MAX_CONCURRENT_REQUESTS: "20"
  MAX_WORKERS: "8"
  
  # Storage settings
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET_NAME: "rag-documents"
  MINIO_SECURE: "false"
  MAX_FILE_SIZE_MB: "100"
  
  # Celery settings
  CELERY_WORKER_CONCURRENCY: "8"
  CELERY_WORKER_PREFETCH_MULTIPLIER: "1"
  CELERY_TASK_SOFT_TIME_LIMIT: "300"
  CELERY_TASK_TIME_LIMIT: "600"
  CELERY_TASK_MAX_RETRIES: "3"
  CELERY_RESULT_EXPIRES: "3600"
  
  # Monitoring settings
  PROMETHEUS_PORT: "9090"
  METRICS_ENABLED: "true"
  TRACING_ENABLED: "true"
  LOG_FORMAT: "json"
  
  # Security settings
  JWT_ALGORITHM: "RS256"
  JWT_EXPIRE_MINUTES: "30"
  JWT_REFRESH_EXPIRE_DAYS: "7"
  KEYCLOAK_REALM: "rag-realm"
  KEYCLOAK_CLIENT_ID: "rag-client"
  
  # External service URLs
  KEYCLOAK_SERVER_URL: "http://keycloak-service:8080"
  ELASTICSEARCH_URL: "http://elasticsearch-service:9200"
  JAEGER_ENDPOINT: "http://jaeger-service:4318"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: enterprise-rag-secrets
  namespace: enterprise-rag
type: Opaque
stringData:
  # Security
  SECRET_KEY: "your-super-secret-key-change-this-in-production"
  JWT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    # Your JWT private key here
    -----END PRIVATE KEY-----
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    # Your JWT public key here
    -----END PUBLIC KEY-----
  
  # API Keys
  OPENAI_API_KEY: "sk-your-openai-api-key"
  COHERE_API_KEY: "your-cohere-api-key"
  ANTHROPIC_API_KEY: "your-anthropic-api-key"
  HUGGINGFACE_API_KEY: "your-huggingface-api-key"
  LANGSMITH_API_KEY: "your-langsmith-api-key"
  
  # Database credentials
  DATABASE_URL: "postgresql+asyncpg://rag_user:rag_password@postgres-service:5432/rag_database"
  POSTGRES_PASSWORD: "rag_password"
  
  # Redis credentials
  REDIS_URL: "redis://:redis_password@redis-service:6379/0"
  REDIS_PASSWORD: "redis_password"
  
  # Vector DB credentials
  QDRANT_API_KEY: "your-qdrant-api-key"
  WEAVIATE_API_KEY: "your-weaviate-api-key"
  
  # Storage credentials
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  
  # Keycloak credentials
  KEYCLOAK_CLIENT_SECRET: "your-keycloak-client-secret"
  KEYCLOAK_ADMIN_PASSWORD: "admin_password"
  
  # Celery broker
  CELERY_BROKER_URL: "redis://:redis_password@redis-service:6379/1"
  CELERY_RESULT_BACKEND: "redis://:redis_password@redis-service:6379/2"
  
  # Elasticsearch credentials
  ELASTICSEARCH_PASSWORD: "elastic_password"
