apiVersion: v1
kind: Namespace
metadata:
  name: enterprise-rag
  labels:
    name: enterprise-rag
    app.kubernetes.io/name: enterprise-rag
    app.kubernetes.io/version: "1.0.0"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: enterprise-rag-quota
  namespace: enterprise-rag
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "20"
    pods: "50"
